networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    volumes:
      - ./uploads:/app/uploads  
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/furshet
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pgpwd4habr
    depends_on:
      - postgres
    networks:
      - dev
      
  frontend:
    build:
        context: ./frontend
    networks:
       - dev

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: furshet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpwd4habr
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  pgdata: