version: "3.9"

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: furshet-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

      - ./frontend/deploy/furshet/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - dev

  backend:
    build:
      context: ./backend/furshet
    container_name: furshet-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/furshet
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pgpwd4habr
    depends_on:
      - postgres
    networks:
      - dev

  postgres:
    image: postgres:17
    container_name: furshet-postgres
    environment:
      POSTGRES_DB: furshet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpwd4habr
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  pgdata: