worker_processes 1;


events {
}

http {
	server {
		listen 80;
		server_name 144.31.165.137;
		
		client_max_body_size 50M;

		location / {
			proxy_pass http://frontend:3000;
		}

		location /api/ {
			proxy_pass http://backend:8000;
		}
		
		location /uploads/ {
			proxy_pass http://backend:8000/api/uploads/;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
		}

		location /media/ {
			proxy_pass http://backend:8000/api/media/;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
		}
	}

}

