version: "3.9"

services:
  frontend:
    build:
      context: ./furshet
    container_name: furshet-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ../../Spring/furshet
    container_name: furshet-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/furshet
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pgpwd4habr
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    image: postgres:17
    container_name: furshet-postgres
    environment:
      POSTGRES_DB: furshet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpwd4habr
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
