spring.application.name=furshet

spring.datasource.url=jdbc:postgresql://localhost:5432/furshet
spring.datasource.username=postgres
spring.datasource.password=pgpwd4habr
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=true

server.server-header=

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5000MB
spring.servlet.multipart.max-request-size=2000MB
server.tomcat.max-swallow-size=5000MB
server.tomcat.max-http-form-post-size=4000MB

server.tomcat.max-part-count=100
server.tomcat.max-part-header-size=50MB

upload.path=/C:/Users/Alex/Desktop/Spring/furshet/src/main/media


spring.mail.host=smtp.yandex.ru
spring.mail.username=furshetnotificaton@yandex.ru
spring.mail.password=csdbtdkyqmvcsbqx
spring.mail.port=465
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true