spring.application.name=furshet

spring.datasource.url=jdbc:postgresql://postgres:5432/furshet
spring.datasource.username=postgres
spring.datasource.password=pgpwd4habr
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=8000

upload.path=/C:/Users/Alex/Desktop/Spring/furshet/src/main/media

server.servlet.context-path=/api